# Generated by Django 4.1.4 on 2022-12-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
